### ISSUE TITLE
[explore]Date picker randomly changes date

### ISSUE THREAD

**Issue by john-bodley** [apache/superset#12704]
The date picker decides to randomly jump to another date without clicking on it.

### Expected results

Dates shouldn't change until clicked.

### Actual results

Dates change when the mouse leaves the 'TIME RANGE' modal.

#### How to reproduce the bug

1. Go to 'Explore'
2. Click on 'TIME RANGE'
2. Choose 'Custom' as the 'RANGE TYPE'
3. Choose 'Specific Date/Time' as the 'START'
4. Click on a date
5. Move the mouse off of the 'TIME RANGE' modal
6. Notice a different date is selected

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zuzana-vej** [comment]
User reported specific trigger this happens: when you move out of the date picker popover. So, e.g., move your mouse position to somewhere over the chart. When you do that, it resets the selected date. So then by the time you go to click "OK", you're confirming a different date than the one you selected.

**Comment by junlincc** [comment]
i have seen similar issues in filter popover, so i suspect this is related antd component. @villebro this looks like a reasonable item going into our bash.

**Comment by junlincc** [comment]
@john-bodley after investigating this issue, I think this behavior is by design. we can either save the change without clicking 'ok' by default, meaning click both ok or outside to save change, or add a cancel button - click cancel to revert, ok the save. 

To solve your immediate user need, we went with the first solution. may revisit in the future.

**Comment by ktmud** [comment]
This should not be by design.  Imagine the following work flow:


https://user-images.githubusercontent.com/335541/105773421-b70f0200-5f18-11eb-97f9-08392ce990ce.mp4

1. I want to change a date
2. I open the popup, click on the date, the date input has updated
3. I expect the date has been updated, and click on "Apply"  directly.
4. The date magically reverts back to the original date.

Bear in mind that most date pickers without a time input will not even have the "OK" button. Once users click on a date, the intent is clear. It's much likely they want to keep the new date than wanting to revert back to the original date.

**Comment by junlincc** [comment]
This issue has been resolved in master. @john-bodley 

https://user-images.githubusercontent.com/67837651/105800395-74b2e880-5f4b-11eb-8a8c-c7bca50450bb.mov
