### ISSUE TITLE
Time Picker - manually entered custom range timestamps don't "stick"

### ISSUE THREAD

**Issue by rusackas** [apache/superset#14004]
When entering a custom time range, I tried to type a date in the input field / time picker. When I do so, and then hit return, the calendar popover goes away, but the date I typed doesn't stick, and instead reverts to what it was before.

### Expected results

I expect hand-entered dates (when valid) to persist.

### Actual results

Cancellation of timepicker popover

#### Screenshots

https://user-images.githubusercontent.com/812905/113941397-dc8b7800-97b3-11eb-987c-1219ff88a797.mp4

#### How to reproduce the bug

In explore, choose custom time range. Enter a date by hand, and hit return

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
@junlincc @zhaoyongjie hopefully minor, but wanted to track it...
