### ISSUE TITLE
[dashboard color][meta data] one of the duplicated color theme 'D3 category 10' show as 'Superset_dafault' in meta data

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16962]
One of the duplicated color theme 'D3 category 10' show as 'Superset_dafault' in meta data

#### How to reproduce the bug

1. Go to Dashboard properties
2. Click on color theme and select D3 category 10 (duplicated, please select each one)
3. Scroll down to 'Advance'
4.Observe the color_theme in meta data
5. See error

### Expected results

Color theme name in properties will match the meta data color name

### Actual results

One of the duplicated color theme 'D3 category 10' show as 'Superset_dafault' in meta data

#### Screenshots
<img width="875" alt="Screen Shot 2021-10-04 at 11 27 44 AM" src="https://user-images.githubusercontent.com/81597121/135905089-7a05c2f0-9851-40d1-9fdb-8723995fe9d9.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by geido** [comment]
Let me have a look at this
